#spring:
#  datasource:
#    username: root
#    password: Zabbix1234#
#    url: jdbc:mysql://192.168.96.188:3306/website?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
#    driver-class-name: com.mysql.cj.jdbc.Driver


value : 1
